-- CreateEnum
CREATE TYPE "OrgStatus" AS ENUM ('ACTIVE', 'PENDING_SETUP', 'SUSPENDED');

-- CreateEnum
CREATE TYPE "FuelType" AS ENUM ('PETROL', 'DIESEL', 'ELECTRIC', 'HYBRID');

-- CreateEnum
CREATE TYPE "VehicleStatus" AS ENUM ('VERIFIED', 'PENDING', 'REJECTED');

-- AlterTable
ALTER TABLE "Org" ADD COLUMN IF NOT EXISTS "slug" TEXT,
ADD COLUMN IF NOT EXISTS "status" "OrgStatus" NOT NULL DEFAULT 'ACTIVE',
ADD COLUMN IF NOT EXISTS "subsidyPercent" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS "baseRideCharge" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS "maxRidersPerCarpool" INTEGER NOT NULL DEFAULT 4,
ADD COLUMN IF NOT EXISTS "autoMatchEnabled" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN IF NOT EXISTS "departmentRestriction" BOOLEAN NOT NULL DEFAULT false;

-- AlterTable
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "employeeId" TEXT,
ADD COLUMN IF NOT EXISTS "carpoolAccess" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN IF NOT EXISTS "rating" DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "Vehicle" ADD COLUMN IF NOT EXISTS "fuelType" "FuelType" NOT NULL DEFAULT 'PETROL',
ADD COLUMN IF NOT EXISTS "status" "VehicleStatus" NOT NULL DEFAULT 'VERIFIED';

-- CreateIndex
CREATE UNIQUE INDEX IF NOT EXISTS "Org_slug_key" ON "Org"("slug");
